export const CLOUD_LOOP_FIRST_TO_LOAD = 1;
export const CLOUD_LOOP_FIRST_FRAME_INDEX = 0;
export const CLOUD_LOOP_LENGTH = 60;

export const CLOUD_TO_LOGO_FIRST_TO_LOAD = 61;
export const CLOUD_TO_LOGO_FIRST_FRAME_INDEX = 60;
export const CLOUD_TO_LOGO_LENGTH = 40;

export const LOGO_TO_PLATTONIC_FIRST_TO_LOAD = 120;
export const LOGO_TO_PLATONIC_FIRST_FRAME_INDEX = 100;
export const LOGO_TO_PLATONIC_LENGTH = 41;

export const PLATONIC_TO_GLOBE_FIRST_TO_LOAD = 60;
export const PLATONIC_TO_GLOBE_FIRST_FRAME_INDEX = 141;
export const PLATONIC_TO_GLOBE_LENGTH = 61;
